name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: IndianGitG/github-actions-reusable-workflow-playground/.github/workflows/reusable_workflow.yml@main
    with:
      message: "Hello from Repo 2!"
