name: Check Token for Private Repo Access

on:
  workflow_dispatch:

jobs:
  test-private-repo-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check Token Access to Private Repo
        env:
          TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Replace with your actual secret name if different
        run: |
          echo "Testing token for private repo access..."
          curl -H "Authorization: token $TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/IndianGitG/github-actions-reusable-workflow-playground/contents/.github/workflows/reusable_workflow.yml" \
               | jq '.name, .path, .download_url'
