name: Check Token Validity

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check Token
        env:
          TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Replace REPO_ACCESS_TOKEN with your token name
        run: |
          echo "Testing token..."
          curl -H "Authorization: token $TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }} \
               | jq .private  # This line uses jq to parse JSON and outputs whether the repo is private
